name: Python CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Tests
      run: pytest

    - name: Run Linters
      run: pylint vnstock

    - name: Run Code Style Check
      run: flake8 vnstock

    - name: Report Test Coverage
      run: coverage run -m pytest
    - name: Upload coverage to Codecov
      run: codecov
